#!/bin/sh

if [ "x${RUNVALID_PREFIX}" != "x" ];
then
PREFIX=${RUNVALID_PREFIX}
else
PREFIX=../../src
fi

echo "---Running tests with the synthetic workload generator---"
echo ""


(cd ../..; make clean)
(cd ../..; make )


echo "Sequential read (250K I/Os): average SSD response time should be around 0.132 ms"
$PREFIX/disksim ssd-sr250k.parv ssd-sr250k.outv ascii 0 1 
grep "ssd Response time average:" ssd-sr250k.outv | grep -v "#"
